### ISSUE TITLE
Caching Unfurl in GitHub workflows

### ISSUE THREAD

**Issue by milesstoetzner** [onecommons/unfurl#266]
Hello,

First of all, thanks for this orchestrator.
I am using it in some acedemic projects.

**I am wondering how to properly cache  an Unfurl installation in a GitHub workflow.**

To give some context: I have a workflow that basically tests if my CSARs still work.
Therefore, I use Unfurl to deploy them.

My goal is to reduce the time of the overall workflow.
Thus, I am trying to cache as much as possible, e.g., unfurl home.
Moreover, I am not required to persist any data, e.g., instance data, since applications will also be undeployed in the workflow.
Also, I think its not a problem to cache any data across branches.

Currently, I have the following job steps (see [here](https://github.com/OpenTOSCA/opentosca-vintner/blob/e18b31ab3b86b539d1a6002a0390568d2514a7c7/.github/workflows/night.yaml) for the complete workflow).

```
- name: (PREPARE) Setup Python
  uses: actions/setup-python@v4
  with:
      python-version: 3.10.13
      cache: pip

- name: (PREPARE) Cache Unfurl
  uses: actions/cache@v3
  with:
      path: /home/runner/.unfurl_home
      key: unfurl-home

- name: (PREPARE) Install Unfurl
  run: pip install unfurl==0.7.1

- name: (PREPARE) Set up Unfurl
  run: yes | unfurl home --init
````

[Here](https://github.com/OpenTOSCA/opentosca-vintner/actions/workflows/night.yaml) are some runs, e.g. [run#17549767170](https://github.com/OpenTOSCA/opentosca-vintner/actions/runs/6464710575/job/17549767170).
As you can see with my approach, installing Unfurl from cache takes roughly 2mins.
This is already an improvement from [7mins clean install](https://github.com/OpenTOSCA/opentosca-vintner/actions/runs/6677267360/job/18147105860).
However, I expected to reduce the installation time to at least 30sec.

What do you think?

I just saw that there is also `unfurl home --restore`.
Is that the way to go? 
How to use it?

Also, would installing `unfurl[full]` improve something?

Best greetings from Germany
Miles
