### ISSUE TITLE
Find unfurl.capabilities.Endpoint.Ansible in Hosting Stack

### ISSUE THREAD

**Issue by milesstoetzner** [onecommons/unfurl#294]
Would it make sense to search for `unfurl.capabilities.Endpoint.Ansible` in the hosting stack and not only in the direct host?

For example, when planning the following ensemble, the Ansible inventory for `app` is empty.
One is required to model the `unfurl.capabilities.Endpoint.Ansible` also at the server proxying the capability of `host`, as depicted by the commented out code.

I tried this with Unfurl 0.9.1 and 1.0.0.

````yaml
apiVersion: unfurl/v1alpha1
kind: Ensemble
spec:
  service_template:
    node_types:
      host:
        derived_from: tosca:Root

        attributes:
          public_address:
            type: string

        capabilities:
          host:
            type: tosca.capabilities.Compute
          endpoint:
            type: unfurl.capabilities.Endpoint.Ansible
            properties:
              connection: ssh
              host: {eval: .::..::public_address}

        interfaces:
          Standard:
            create:
              implementation:
                primary: Ansible
                operation_host: ORCHESTRATOR
              inputs:
                resultTemplate: |
                  - name: SELF
                    attributes:
                      public_address: "{{ outputs.public_address | trim }}"  
                playbook:
                  q:
                  - name: Sets a fact
                    set_fact:
                      public_address: ansible_public_address
              outputs:
                public_address:

      server:
        derived_from: tosca.nodes.SoftwareComponent
        capabilities:
          #endpoint:
          #  type: unfurl.capabilities.Endpoint.Ansible
          #  properties:
          #    connection: {eval: '.::..::.requirements[.name=host]::.target::.capabilities[.name=endpoint]::connection'}
          #    host: {eval: '.::..::.requirements[.name=host]::.target::public_address'}
          host:
            type: tosca.capabilities.Compute

        interfaces:
          Standard:
            create:
              implementation: exit 0

      app:
        derived_from: tosca.nodes.SoftwareComponent
        properties:
          os_ssh_user:
            type: string
            default: ubuntu

          os_ssh_key_file:
            type: string
            default: /path/to/key/file

        interfaces:
          Standard:
            create:
              implementation:
                primary: Ansible
                operation_host: HOST
              inputs:
                playbook:
                  q:
                  - name: Wait for ssh
                    wait_for_connection:
                playbookArgs:
                - --key-file={{ SELF.os_ssh_key_file }}
                - --user={{ SELF.os_ssh_user }}
                - --ssh-common-args="-o IdentitiesOnly=yes -o BatchMode=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"


    topology_template:
      node_templates:
        host:
          type: host

        server:
          type: server
          requirements:
          - host: host

        app:
          type: app
          requirements:
          - host: server
````

I think the required change would be applied somewhere here:
https://github.com/onecommons/unfurl/blob/a34e29ba120d2db0afe297c8ce23c7ff7ffe4f26/unfurl/configurators/ansible.py#L152

Or am I missing something? 

Best Greetings
Miles
