### ISSUE TITLE
unfurl.capabilities.Endpoint.Ansible ignores credential and hostvars 

### ISSUE THREAD

**Issue by milesstoetzner** [onecommons/unfurl#295]
The documentation states that Unfurl respects the `credential` property of `unfurl.capabilities.Endpoint.Ansible`. 

https://github.com/onecommons/unfurl/blob/a34e29ba120d2db0afe297c8ce23c7ff7ffe4f26/docs/configurators.rst?plain=1#L112-L113

However, when I tried this using Unfurl 0.9.1 and 1.0.0, it seems not to work.
Here is an example.

````yaml
apiVersion: unfurl/v1alpha1
kind: Ensemble
spec:
  service_template:
    node_types:
      host:
        derived_from: tosca:Root

        attributes:
          public_address:
            type: string

        capabilities:
          host:
            type: tosca.capabilities.Compute
          endpoint:
            type: unfurl.capabilities.Endpoint.Ansible
            properties:
              connection: ssh
              host: {eval: .::..::public_address}
              user: ubuntu
              credential:
                token_type: ssh_private_key_file
                token: /path/to/key/file

        interfaces:
          Standard:
            create:
              implementation:
                primary: Ansible
                operation_host: ORCHESTRATOR
              inputs:
                resultTemplate: |
                  - name: SELF
                    attributes:
                      public_address: "{{ outputs.public_address | trim }}"  
                playbook:
                  q:
                  - name: Sets a fact
                    set_fact:
                      public_address: ansible_public_address
              outputs:
                public_address:

      app:
        derived_from: tosca.nodes.SoftwareComponent
        interfaces:
          Standard:
            create:
              implementation:
                primary: Ansible
                operation_host: HOST
              inputs:
                playbook:
                  q:
                  - name: Wait for ssh
                    wait_for_connection:
                playbookArgs:
                - --ssh-common-args="-o IdentitiesOnly=yes -o BatchMode=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

    topology_template:
      node_templates:
        host:
          type: host

        app:
          type: app
          requirements:
          - host: host
````

````yaml
all:
  hosts:
    host:
      ansible_host: ansible_public_address
      ansible_connection: ssh
      ansible_user: ubuntu
  vars: {}
  children: {}
````

It seems to be extracted only for `unfurl.relationships.ConnectsTo.Ansible` but not for `unfurl.capabilities.Endpoint.Ansible`.

https://github.com/onecommons/unfurl/blob/a34e29ba120d2db0afe297c8ce23c7ff7ffe4f26/unfurl/configurators/ansible.py#L157

I think this also applies to `hostvars`.

Am I missing something?

Best Greetings
Miles

**Comment by milesstoetzner** [comment]
I just noted, that when the capability properties are modeled in the node template and not in the node type, then a parse error is thrown. That does not fix the claim in the docs but at least is consistent to my experience that its not supported.

````
    topology_template:
      node_templates:
        host:
          type: host
          capabilities:
            endpoint:
              properties:
                connection: ssh
                host: {eval: .::..::public_address}
                user: ubuntu
                credential:
                  token_type: ssh_private_key_file
                  token: /path/to/key/file

        app:
          type: app
          requirements:
          - host: host
```` 


````
UnknownFieldError: "properties" of template "host" contains unknown field "credential". Refer to the definition to verify valid values. in node template "host"
````

**Comment by aszs** [comment]
As the UnknownFieldError you shared indicates the problem is that `unfurl.capabilities.Endpoint.Ansible` doesn't define a `credentials` property.  Here's your example updated so that it works:

```yaml
apiVersion: unfurl/v1alpha1
kind: Ensemble
spec:
  service_template:
    node_types:
      Host:
        derived_from: tosca:Root

        attributes:
          public_address:
            type: string

        capabilities:
          host:
            type: tosca.capabilities.Compute
          endpoint:
            type: unfurl.capabilities.Endpoint.Ansible

        interfaces:
          Standard:
            create:
              implementation:
                primary: Ansible
                operation_host: ORCHESTRATOR
              inputs:
                resultTemplate: |
                  - name: SELF
                    attributes:
                      public_address: "{{ outputs.public_address | trim }}"  
                playbook:
                  q:
                  - name: Sets a fact
                    set_fact:
                      public_address: ansible_public_address
              outputs:
                public_address:

      App:
        derived_from: tosca.nodes.SoftwareComponent
        interfaces:
          Standard:
            create:
              implementation:
                primary: Ansible
                operation_host: HOST
              inputs:
                playbook:
                  q:
                  - name: Wait for ssh
                    wait_for_connection:
                playbookArgs:
                - --ssh-common-args="-o IdentitiesOnly=yes -o BatchMode=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

    topology_template:
      node_templates:
        host:
          type: Host
          capabilities:
            endpoint:
              properties:
                connection: ssh
                host: {eval: ..::public_address}
        app:
          type: App
          requirements:
          - host: host
  
      relationship_templates:
        host_connection:
          default_for: host
          type: unfurl.relationships.ConnectsTo.Ansible
          properties:
            credential:
              user: ubuntu
              token_type: ssh_private_key_file
              token: /path/to/key/file
```

With that change after running `unfurl deploy --dryrun` the rendered `inventory.yaml` for `app` looks like what you'd expect:

```yaml
all:
  hosts:
    host:
      ansible_host: ansible_public_address
      ansible_connection: ssh
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /path/to/key/file
  vars: {}
  children: {}
```

Let me breakdown what's going on. First, as you noted, the docs are wrong, it mixed up the capability and the relationship, I've fixed it so it now reads:

```
* If the ``operation_host`` has an ``endpoint`` of  type ``unfurl.capabilities.Endpoint.SSH`` or ``unfurl.capabilities.Endpoint.Ansible``
  use that capabilities ``host``, ``port``, ``connection``, ``user``, and ``hostvars`` properties.
* If the ``operation_host`` has relationship template or connection to the target instance of
  type ``unfurl.relationships.ConnectsTo.Ansible`` uses its ``credential`` and ``hostvars`` properties.
```

Second, TOSCA 1.3 says that the capability section on a type definition should be capability type definition, not a capability declaration, that needs to be on the template. Unfortunately, I just checked the code for the tosca parser unfurl relies on and it just silently ignores the malformed capability, which is why you didn't get an error. 

Finally, the easiest way to set the Ansible connection properties on the relationship is to define a default relationship template for `host`. This way any node that needs to access `host` via ansible will use those properties.
