### ISSUE TITLE
Filters on Artifacts

### ISSUE THREAD

**Issue by milesstoetzner** [onecommons/unfurl#338]
Does Unfurl support filters in eval expressions in the context of artifacts?

I successfully use filters in eval  expressions in the context of requirements, e.g., `eval: .::.requirements::[.name=host]::.target::management_address`. 
However, this seems not to work on artifacts.

Here is a minimal ensemble.
My goal is to access `file` of the artifact of type `my_artifact_type`.

````
apiVersion: unfurl/v1alpha1
kind: Ensemble
spec:
  service_template:
    artifact_types:
      my_artifact_type:
        derived_from: tosca.artifacts.Root

    topology_template:
      node_templates:
        my_app:
          type: tosca.nodes.Root

          interfaces:
            Standard:
              operations:
                create:
                  implementation: Ansible
                  inputs:
                    playbook:
                      q:
                      - shell: echo '{{ ".artifacts::[.type=my_artifact_type]::.file" | eval }}'> /tmp/issue-338
                      - shell: exit 1

          artifacts:
            my_artifact:
              type: my_artifact_type
              file: some_value
````

However, it does not find it.
You can check this by running.

```
rm -f /tmp/issue-338 && unfurl deploy -a && cat /tmp/issue-338
```

I tried this on Unfurl v1.0.0 and v1.1.0. 

Note, `{{ ".artifacts::my_artifact::.file" | eval }}` works perfect. 
But I have a use case, where I don't want to limit the naming of the artifact but find it dynamically. 

Alternatively, for my specific use case, we can assume that there is at max a single artifact.
So is there a way to access the `file` of "the only assigned artifact", e.g., accessing index 0 like `{{ ".artifacts::0::.file" | eval }}`?

Best regards
Miles
