### ISSUE TITLE
Accessing the Implementation of a Management Operation in another Managment Operation

### ISSUE THREAD

**Issue by milesstoetzner** [onecommons/unfurl#339]
I have a rather strange use case, but I need to access the implementation of a management operation in another management operation.

So in the following simple example, I want to access the value of the implementation of the operation `create` at the interface `Management`, i.e., `management.configure`, and use it in the playbook of the operation `create` in the interface `Standard`.  
I actually managed to do this utilizing a python script proxied via the default value of `_management_configure`.

However, I am wondering if there is a smarter way to do this without using such a proxy property or even without the python script?

```
# project_root/ensemble/ensemble.yaml

apiVersion: unfurl/v1alpha1
kind: Ensemble
spec:
  service_template:
    interface_types:
      management:
        derived_from: tosca.interfaces.Root
        operations:
          create:
          configure:
          start:
          stop:
          delete:

    node_types:
      my_app:
        derived_from: tosca.nodes.Root

        properties:
          _management_configure:
            type: string
            default:
              eval:
                python: '{{ "project" | get_dir }}/utils.py#get_operation'
                args:
                - Management
                - configure

        interfaces:
          Management:
            type: management

    topology_template:
      node_templates:
        my_app:
          type: my_app

          interfaces:
            Standard:
              operations:
                create:
                  implementation: Ansible
                  inputs:
                    playbook:
                      q:
                      - shell: echo '{{ SELF._management_configure }}' > /tmp/issue-339
                      - shell: exit 1

            Management:
              type: management
              operations:
                configure: management.configure
                delete: management.delte
```

Here is the python script.

```
# project_root/utils.py

def get_operation(ctx, args):
    if args == None or len(args) != 2: 
        raise AssertionError('Interface and operation name are required as inputs')

    interface = args[0]
    operation = args[1]

    operations = ctx.currentResource.template.get_interfaces()

    filtered = list(filter(lambda x: x.interfacename == interface and x.name == operation, operations))
    if len(filtered) != 1:
        return None
    
    return filtered[0].value.get('implementation')
```

I use the following command to play around. 

```
rm -f /tmp/issue-339 && unfurl deploy -a && cat /tmp/issue-339
```

Best regards
Miles

**Comment by aszs** [comment]
I can't think of better way to do this than your python function but you can delegate to other operations using our "invoke" extension, maybe that would be a cleaner approach? For example:

```yaml
      Standard:
        operations:
          configure:
            invoke: Helm.execute
            inputs:
              helmcmd: '{{ "upgrade" if ".::.present" | eval else "install"}}'
```
(i copied that from https://github.com/onecommons/unfurl/blob/main/unfurl/configurators/templates/helm.yaml#L214)
