### ISSUE TITLE
Validate Assigned Types

### ISSUE THREAD

**Issue by milesstoetzner** [onecommons/unfurl#342]
Following https://github.com/onecommons/unfurl/issues/341, it would be great if there is a validation that, e.g., an interface type can not be assigned to a node template or artifact definition.

The following simple example does not throw a validation error even tho an interface type is assigned to a node template and artifact definition.

```
apiVersion: unfurl/v1alpha1
kind: Ensemble
spec:
  service_template:
    interface_types:
      my_interface_type:
        derived_from: tosca.interfaces.Root

    topology_template:
      node_templates:
        my_app:
          type: my_interface_type # <--- invalid
          
          artifacts:
            my_artifact:
              type: my_interface_type # <--- invalid
              file: my_artifact_file
 ```
 
 I tried this on Unfurl v1.0.0 and v1.1.0.
 
 Best regards
 Miles
