### ISSUE TITLE
Quickstart tutorial: Malformed image URL on docker-compose

### ISSUE THREAD

**Issue by juancadavid** [onecommons/unfurl#350]
Hi there,
I'm new to Unfurl and started doing the quickstart tutorial. I've had several issues that the page doesn't mention and I was able to fix but I'll contribute detailed feedback once I get it to work. 
I'm trying to deploy the local development blueprint on k8s. The generated `development/active/tasks/host/docker-compose.yml` file is looking like this:

```
services:
  development-host:
    restart: always
    environment:
      DBASE: postgresql://root:0xRG3CicBUXkW43@development-db--host--requirement.myproject:5432/my_db
    image: registry.gitlab.com/registry.gitlab.com/gitlab-org/project-templates/express/main:latest
    ports:
    - 5000:5000
    labels:
      kompose.volume.size: 10 GiB
      kompose.image-pull-policy: Always
      kompose.service.expose: myapp.myproject.jcadavid.home.u.opencloudservices.net
version: '3.7'
```

As you can see, the image URL is prepending the url host `registry.gitlab.com` twice, although in `service_template.py` it is correctly specified: 

```
# This file is included by ensemble-template.yaml 
# You can define TOSCA types and templates here in Python, see 
# https://github.com/onecommons/unfurl/blob/main/tosca-package/README.md

# for example:

import tosca

# uncomment if you declared the "std" repository in ensemble-template.yaml
from tosca_repositories import std

# class MyNodeType(tosca.nodes.Root):
#     name: str
from tosca_repositories.std.aws.compute import EC2Compute
from tosca_repositories.std.aws.db import AwsRdsPostgres
from tosca_repositories.std import k8s
from tosca_repositories.std.dns_services import Route53DNSZone

import unfurl
from unfurl.configurators.templates.docker import unfurl_datatypes_DockerContainer
from tosca import Size, TopologyInputs, GB, MB
from tosca_repositories import std

class Inputs(TopologyInputs):
    disk_size: Size = 10 * GB
    mem_size: Size = 2048 * MB

db = std.PostgresDB()

host = std.ContainerHost()

container = std.ContainerService(
    environment=unfurl.datatypes.EnvironmentVariables(
        DBASE=db.url, URL=std.SQLWebApp.url 
    ),
    host_requirement=host,
    container=unfurl_datatypes_DockerContainer(
        image="registry.gitlab.com/gitlab-org/project-templates/express/main:latest",
        ports=["5000:5000"],

        #deploy={"resources": {"limits": {"memory": Inputs.mem_size}}},
    ),
)

__root__ = std.SQLWebApp(container=container, db=db, subdomain="myapp" )

class production(tosca.DeploymentBlueprint):
    _cloud = unfurl.relationships.ConnectsToAWSAccount

    host = std.HttpsProxyContainerComputeHost(
        host=EC2Compute(
            disk_size=Inputs.disk_size,
            num_cpus=2,
            mem_size=Inputs.mem_size,
        ),
        dns=Route53DNSZone(name="example.com"),
    )
    db = AwsRdsPostgres()

class dev(tosca.DeploymentBlueprint):
    # unfurl_relationships_ConnectsTo_K8sCluster
    _cloud = "unfurl.relationships.ConnectsTo.K8sCluster"

    host = k8s.PublicK8sContainerHost(
        labels={"kompose.volume.size": Inputs.disk_size},
    )
    db = std.PostgresDBInstance(
        database_name="my_db", host_requirement=k8s.PrivateK8sContainerHost()
    )
```
Therefore, I'm having the current issue on the `development-host` node of my local k8s cluster: 

```
Failed to pull image "registry.gitlab.com/registry.gitlab.com/gitlab-org/project-templates/express/main": failed to pull and unpack image "registry.gitlab.com/registry.gitlab.com/gitlab-org/project-templates/express/main:latest": failed to resolve reference "registry.gitlab.com/registry.gitlab.com/gitlab-org/project-templates/express/main:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

It says something about authorization (which shouldn't be required but I did do `docker login` just in case), but it's clearly a problem with the URL.

All other nodes in k8s are created and run correctly. Thanks in advance for any help.

Juan
